version: "2"
services: 
  web:
    build: 
      context: nginx
      dockerfile: Dockerfile
    container_name: server-nginx
    env_file:
      - ".env"
    volumes: 
      - "${WEB_APP}:/var/www/html"
    ports: 
      - 80:80
    working_dir: /var/www/html
    links: 
      - php
  php:
    image: php:7.4-fpm
    container_name: php-fpm
    env_file:
      - ".env"
    volumes:
      - "${WEB_APP}:/var/www/html"
    ports: 
      - 9000:9000
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: db-mysql
    restart: always
    env_file:
      - ".env"
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports: 
      - 3306:3306
    networks:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports: 
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
    links: 
      - mysql
    networks:
      - db
networks: 
  db: